apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-microservice
  template:
    metadata:
      labels:
        app: shop-microservice
    spec:
      containers:
      - name: shop-microservice
        image: shop-microservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: shop-service
spec:
  type: NodePort
  selector:
    app: shop-microservice
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30007

